channels:
- conda-forge
dependencies:
- python=3.8.0
- pip
- pip:
  - mlflow
  - cloudpickle==3.0.0
  - psutil==5.9.8
  - scikit-learn==0.23.2
  - typing-extensions==4.10.0
name: mlflow-env
